### PR TITLE
Fix assigning expressions to Mapped attributes.

### LINKED ISSUE #68: Assigning functions to orm attributes
**Describe the bug**
Introduced by #40, `sql.functions` are no longer able to be assigned to ORM attributes. I couldn't find documented cases of directly assigning functions to attributes. Is it even a supported use-case? Or should `update()` always be used.

**Expected behavior**
Type checking to pass, as it works at runtime

**To Reproduce**

```py
from sqlalchemy import Column, DateTime
from sqlalchemy import Integer
from sqlalchemy.orm import registry
from sqlalchemy.sql.functions import now

mapper_registry: registry = registry()

@mapper_registry.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    date_time = Column(DateTime())

a = A()
a.date_time = now()
```

**Error**

```
test/ext/mypy/files/function_now.py:15: error: Incompatible types in assignment (expression has type "now[<nothing>]", variable has type "Optional[datetime]")```
```
**Have a nice day!**

### PR DESCRIPTION
**Pull request by MaicoTimmerman**
### Description
Allow for assigning expressions to mapped attributes. Fixes #68.

I tried to use `ColumnElement[_T]`, however since `sqlalchemy.sql.operators.ColumnOperators` all return `ClauseElement`, this is not possible. Perhaps the operators need to return `ColumnElement`?

Used test-file:
  
```py
from sqlalchemy import Column, DateTime, create_engine
from sqlalchemy import Integer
from sqlalchemy.orm import registry, Session
from sqlalchemy.sql.functions import now

mapper_registry: registry = registry()

e = create_engine('sqlite:///database.db')


@mapper_registry.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    integer = Column(Integer)
    date_time = Column(DateTime())


with Session(e) as s:
    a = A(integer=1)
    a.integer = A.integer + 1
    a.date_time = now()
    s.add(a)
    s.commit()
```

### Checklist

This pull request is:

- [ ] A documentation / typographical error fix
	- Good to go, no issue or tests are needed
- [x] A short code fix
	- please include the issue number, and create an issue if none exists, which
	  must include a complete example of the issue.  one line code fixes without an
	  issue and demonstration will not be accepted.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.   one line code fixes without tests will not be accepted.
- [ ] A new feature implementation
	- please include the issue number, and create an issue if none exists, which must
	  include a complete example of how the feature would look.
	- Please include: `Fixes: #<issue number>` in the commit message
	- please include tests.

**Have a nice day!**

### CODE REVIEW

File: sqlalchemy-stubs/orm/attributes.pyi [hunk 1]
```diff
@@ -91,7 +92,10 @@ class Mapped(QueryableAttribute, Generic[_T]):
     def __get__(self, instance: None, owner: Any) -> "Mapped"[_T]: ...
     @overload
     def __get__(self, instance: object, owner: Any) -> _T: ...
+    @overload
     def __set__(self, instance: Any, value: _T) -> None: ...
+    @overload
+    def __set__(self, instance: Any, value: ClauseElement) -> None: ...
```
Comment (bryanforbes) [inline sqlalchemy-stubs/orm/attributes.pyi:98]: This should be `ColumnElement[TypeEngine[_T]]`

Comment (MaicoTimmerman) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: I tried this with #71, but this runs into errors for assigning `now()` as :
```
Incompatible types in assignment (expression has type "now[DateTime]", variable has type "ColumnElement[TypeEngine[Optional[datetime]]]")
```

The `a.integer = A.integer + 1` seems to crash mypy somewhere when inferring overloads, but I'm not sure if that is caused by #71 or this change.

Comment (MaicoTimmerman) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: I think we are running into a covariance issue here, but I'm unsure how to solve it.

Given this test-case:

```py
from datetime import datetime

from sqlalchemy import Column, create_engine, DateTime, Integer
from sqlalchemy.orm import registry, Mapped, Session
from sqlalchemy.sql.functions import now

mapper_registry: registry = registry()
e = create_engine("sqlite:///database.db", echo=True)

@mapper_registry.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    date_time: Mapped[datetime] = Column(DateTime())
    date_time2 = Column(DateTime())

mapper_registry.metadata.create_all(e)

with Session(e) as s:
    a = A()
    a.date_time = now()
    a.date_time2 = now()
    s.add(a)
    s.commit()
```

I tried to adapt the `ColumnElement` type parameter to be covariant. It then correctly accepts `ColumnElement[TypeEngine[datetime]]` for `row[DateTime]`, however that does not solve the case `Mapped[Optional[datetime]]` case.

Comment (bryanforbes) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: I just tried your changes listed here rebased on top of the latest from `master` and the test case you have above passes. Do we still need the covariant solution?

Comment (MaicoTimmerman) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: That is because the PR still contains the broad `ClauseElement`, instead of the `ColumnElement[TypeEngine[_T]]`. I didn't update the PR to be broken. Using `ColumnElement[TypeEngine[_T]]` as `value` results in:

```
mapped_assign_expression.py:21: error: Incompatible types in assignment (expression has type "now[DateTime]", variable has type "ColumnElement[TypeEngine[datetime]]")
mapped_assign_expression.py:22: error: Incompatible types in assignment (expression has type "now[DateTime]", variable has type "ColumnElement[TypeEngine[Optional[datetime]]]")
```

Comment (bryanforbes) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: Oh, I understand. I'll play with this today and see what I can come up with for a fix.

Comment (MaicoTimmerman) [reply sqlalchemy-stubs/orm/attributes.pyi:98]: As [discussed](https://gitter.im/sqlalchemy/devel/archives/2021/05/05) we will leave this `ClauseElement` for now and try to narrow it later.

**Review by bryanforbes — APPROVED** [review]
