### ISSUE TITLE
Assigning functions to orm attributes

### ISSUE THREAD

**Issue by MaicoTimmerman** [sqlalchemy/sqlalchemy2-stubs#68]
**Describe the bug**
Introduced by #40, `sql.functions` are no longer able to be assigned to ORM attributes. I couldn't find documented cases of directly assigning functions to attributes. Is it even a supported use-case? Or should `update()` always be used.

**Expected behavior**
Type checking to pass, as it works at runtime

**To Reproduce**

```py
from sqlalchemy import Column, DateTime
from sqlalchemy import Integer
from sqlalchemy.orm import registry
from sqlalchemy.sql.functions import now

mapper_registry: registry = registry()

@mapper_registry.mapped
class A:
    __tablename__ = "a"
    id = Column(Integer, primary_key=True)
    date_time = Column(DateTime())

a = A()
a.date_time = now()
```

**Error**

```
test/ext/mypy/files/function_now.py:15: error: Incompatible types in assignment (expression has type "now[<nothing>]", variable has type "Optional[datetime]")```
```
**Have a nice day!**

**Comment by zzzeek** [comment]
that's definitely supported:

https://docs.sqlalchemy.org/en/14/orm/persistence_techniques.html#embedding-sql-insert-update-expressions-into-a-flush
